# Generated by Django 3.1.4 on 2021-01-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcatalog',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
