# Generated by Django 3.1.4 on 2021-01-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_catalog_blog'),
        ('blog', '0002_auto_20210102_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog'),
            preserve_default=False,
        ),
    ]
