# Generated by Django 3.1.4 on 2021-01-02 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('full_catalog', '0001_initial'),
        ('catalog', '0002_remove_catalog_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='full_catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='full_catalog.fullcatalog'),
            preserve_default=False,
        ),
    ]
